### ISSUE TITLE
get error when doing search

### ISSUE THREAD

**Issue by hnpanther** [Alfresco/alfresco-content-app#2936]
Hello
I used alfresco community edition 7.3
When I perform search operation, the program stops and the following error is displayed(in terminal):
```
_http_server.js:259
    throw new ERR_HTTP_INVALID_STATUS_CODE(originalStatusCode);
    ^

RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: 0
    at new NodeError (internal/errors.js:322:7)
    at ServerResponse.writeHead (_http_server.js:259:11)
    at ServerResponse._implicitHeader (_http_server.js:250:8)
    at ServerResponse.end (_http_outgoing.js:837:10)
    at IncomingMessage.onend (internal/streams/readable.js:670:10)
    at Object.onceWrapper (events.js:519:28)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'ERR_HTTP_INVALID_STATUS_CODE'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! alfresco-content-app@4.0.0-A.2 start: `ng serve "content-ce"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the alfresco-content-app@4.0.0-A.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user1\AppData\Roaming\npm-cache\_logs\2023-01-28T09_54_01_558Z-debug.log
```

**Comment by hnpanther** [comment]
log file:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start',
1 verbose cli   'content-ce'
1 verbose cli ]
2 info using npm@6.14.17
3 info using node@v14.21.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle alfresco-content-app@4.0.0-A.2~prestart: alfresco-content-app@4.0.0-A.2
6 verbose lifecycle alfresco-content-app@4.0.0-A.2~prestart: unsafe-perm in lifecycle true
7 verbose lifecycle alfresco-content-app@4.0.0-A.2~prestart: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\user1\Desktop\aca\alfresco-content-app-develop\node_modules\.bin;C:\Program Files\Eclipse Adoptium\jdk-11.0.18.10-hotspot\bin;C:\Program Files\Eclipse Adoptium\jdk-17.0.5.8-hotspot\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\OpenSSL-Win64\bin;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\MySQL\MySQL Shell 8.0\bin\;C:\Users\user1\AppData\Local\Microsoft\WindowsApps;C:\Program Files\OpenSSL-Win64\bin;C:\Users\user1\AppData\Roaming\npm
8 verbose lifecycle alfresco-content-app@4.0.0-A.2~prestart: CWD: C:\Users\user1\Desktop\aca\alfresco-content-app-develop
9 silly lifecycle alfresco-content-app@4.0.0-A.2~prestart: Args: [
9 silly lifecycle   '/d /s /c',
9 silly lifecycle   'npm run assemble-app-config && npm run validate-app-config'
9 silly lifecycle ]
10 silly lifecycle alfresco-content-app@4.0.0-A.2~prestart: Returned: code: 0  signal: null
11 info lifecycle alfresco-content-app@4.0.0-A.2~start: alfresco-content-app@4.0.0-A.2
12 verbose lifecycle alfresco-content-app@4.0.0-A.2~start: unsafe-perm in lifecycle true
13 verbose lifecycle alfresco-content-app@4.0.0-A.2~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\user1\Desktop\aca\alfresco-content-app-develop\node_modules\.bin;C:\Program Files\Eclipse Adoptium\jdk-11.0.18.10-hotspot\bin;C:\Program Files\Eclipse Adoptium\jdk-17.0.5.8-hotspot\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\OpenSSL-Win64\bin;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\MySQL\MySQL Shell 8.0\bin\;C:\Users\user1\AppData\Local\Microsoft\WindowsApps;C:\Program Files\OpenSSL-Win64\bin;C:\Users\user1\AppData\Roaming\npm
14 verbose lifecycle alfresco-content-app@4.0.0-A.2~start: CWD: C:\Users\user1\Desktop\aca\alfresco-content-app-develop
15 silly lifecycle alfresco-content-app@4.0.0-A.2~start: Args: [ '/d /s /c', 'ng serve "content-ce"' ]
16 silly lifecycle alfresco-content-app@4.0.0-A.2~start: Returned: code: 1  signal: null
17 info lifecycle alfresco-content-app@4.0.0-A.2~start: Failed to exec start script
18 verbose stack Error: alfresco-content-app@4.0.0-A.2 start: `ng serve "content-ce"`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
18 verbose stack     at EventEmitter.emit (events.js:400:28)
18 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
18 verbose stack     at ChildProcess.emit (events.js:400:28)
18 verbose stack     at maybeClose (internal/child_process.js:1088:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
19 verbose pkgid alfresco-content-app@4.0.0-A.2
20 verbose cwd C:\Users\user1\Desktop\aca\alfresco-content-app-develop
21 verbose Windows_NT 10.0.20348
22 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start" "content-ce"
23 verbose node v14.21.2
24 verbose npm  v6.14.17
25 error code ELIFECYCLE
26 error errno 1
27 error alfresco-content-app@4.0.0-A.2 start: `ng serve "content-ce"`
27 error Exit status 1
28 error Failed at the alfresco-content-app@4.0.0-A.2 start script.
28 error This is probably not a problem with npm. There is likely additional logging output above.
29 verbose exit [ 1, true ]

```

**Comment by DenysVuika** [comment]
can you please retest this? it might have been related to older versions of the node or dev server
